In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('data/Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [4]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
# OneHot encode geography
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
X = data.drop('EstimatedSalary',axis=1)
y = data['EstimatedSalary']

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [10]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
with open('models/Reg_label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('models/Reg_onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('models/Reg_scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

c:\Users\sumit\OneDrive\Desktop\StayOrGo\stayorgo\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 100192.3281 - mae: 100192.3281 - val_loss: 98487.6562 - val_mae: 98487.6562
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99414.2344 - mae: 99414.2344 - val_loss: 96764.8281 - val_mae: 96764.8281
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 97882.3047 - mae: 97882.3047 - val_loss: 92401.7656 - val_mae: 92401.7656
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 91601.0156 - mae: 91601.0156 - val_loss: 85268.7734 - val_mae: 85268.7734
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 86040.7344 - mae: 86040.7344 - val_loss: 76298.4297 - val_mae: 76298.4297
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 75721.0938 - mae: 75721.0938 - val_loss: 67212.7109 - val_mae: 67212.7109
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 66613.2734 - mae: 66613.2734 - val_loss: 59799.5586 - val_mae: 59799.5586
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 59097.6133 - mae: 59097.6133 - val_loss: 54792.0977 - val_mae: 54792.0977
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53882.7695 - mae: 53882.7695 - val_loss: 52232.1445 - val_mae: 52232.1445
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52452.8984 - mae: 52452.8984 - val_loss: 51211.2383 - val_mae: 51211.2383
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51301.1953 - mae: 51301.1953 - val_loss: 50902.8047 - val_mae: 50902.8047
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50515.1250 - mae: 50515.1250 - val_loss: 50810.1758 - val_mae: 50810.1758
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50931.9219 - mae: 50931.9219 - val_loss: 50759.2148 - val_mae: 50759.2148
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50833.8711 - mae: 50833.8711 - val_loss: 50724.8203 - val_mae: 50724.8203
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50771.7031 - mae: 50771.7031 - val_loss: 50682.6055 - val_mae: 50682.6055
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50439.0156 - mae: 50439.0156 - val_loss: 50665.5195 - val_mae: 50665.5195
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49973.6953 - mae: 49973.6953 - val_loss: 50633.6523 - val_mae: 50633.6523
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50007.2852 - mae: 50007.2852 - val_loss: 50603.5977 - val_mae: 50603.5977
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49891.2812 - mae: 49891.2812 - val_loss: 50592.3477 - val_mae: 50592.3477
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49504.5938 - mae: 49504.5938 - val_loss: 50573.9883 - val_mae: 50573.9883
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50039.5352 - mae: 50039.5352 - val_loss: 50536.9219 - val_mae: 50536.9219
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49887.3945 - mae: 49887.3945 - val_loss: 50518.2188 - val_mae: 50518.2188
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49474.8750 - mae: 49474.8750 - val_loss: 50509.5586 - val_mae: 50509.5586
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49845.2188 - mae: 49845.2188 - val_loss: 50483.7109 - val_mae: 50483.7109
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50016.5859 - mae: 50016.5859 - val_loss: 50468.6406 - val_mae: 50468.6406
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49795.4727 - mae: 49795.4727 - val_loss: 50461.7656 - val_mae: 50461.7656
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49807.2812 - mae: 49807.2812 - val_loss: 50451.3906 - val_mae: 50451.3906
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49738.3047 - mae: 49738.3047 - val_loss: 50430.3711 - val_mae: 50430.3711
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49840.5391 - mae: 49840.5391 - val_loss: 50425.1602 - val_mae: 50425.1602
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49212.6914 - mae: 49212.6914 - val_loss: 50416.1016 - val_mae: 50416.1016
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49629.0508 - mae: 49629.0508 - val_loss: 50402.3359 - val_mae: 50402.3359
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49860.3594 - mae: 49860.3594 - val_loss: 50396.5391 - val_mae: 50396.5391
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49556.1367 - mae: 49556.1367 - val_loss: 50380.7695 - val_mae: 50380.7695
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49715.6055 - mae: 49715.6055 - val_loss: 50370.0195 - val_mae: 50370.0195
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49426.5781 - mae: 49426.5781 - val_loss: 50358.9453 - val_mae: 50358.9453
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48758.0117 - mae: 48758.0117 - val_loss: 50360.4727 - val_mae: 50360.4727
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49880.3359 - mae: 49880.3359 - val_loss: 50343.8672 - val_mae: 50343.8672
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49674.6641 - mae: 49674.6641 - val_loss: 50339.8438 - val_mae: 50339.8438
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49936.6523 - mae: 49936.6523 - val_loss: 50331.8789 - val_mae: 50331.8789
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49876.2266 - mae: 49876.2266 - val_loss: 50327.5859 - val_mae: 50327.5859
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50004.9102 - mae: 50004.9102 - val_loss: 50334.1992 - val_mae: 50334.1992
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49971.8242 - mae: 49971.8242 - val_loss: 50321.1562 - val_mae: 50321.1562
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49309.1406 - mae: 49309.1406 - val_loss: 50317.5703 - val_mae: 50317.5703
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49534.7383 - mae: 49534.7383 - val_loss: 50309.7539 - val_mae: 50309.7539
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50079.5625 - mae: 50079.5625 - val_loss: 50317.0586 - val_mae: 50317.0586
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49376.8477 - mae: 49376.8477 - val_loss: 50299.1445 - val_mae: 50299.1445
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49345.4844 - mae: 49345.4844 - val_loss: 50302.1680 - val_mae: 50302.1680
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49488.1719 - mae: 49488.1719 - val_loss: 50291.8906 - val_mae: 50291.8906
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49886.0273 - mae: 49886.0273 - val_loss: 50287.2148 - val_mae: 50287.2148
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49884.4922 - mae: 49884.4922 - val_loss: 50287.3477 - val_mae: 50287.3477
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49499.5820 - mae: 49499.5820 - val_loss: 50277.8672 - val_mae: 50277.8672
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49852.6836 - mae: 49852.6836 - val_loss: 50289.5859 - val_mae: 50289.5859
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49897.5547 - mae: 49897.5547 - val_loss: 50285.3594 - val_mae: 50285.3594
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49441.7148 - mae: 49441.7148 - val_loss: 50282.1211 - val_mae: 50282.1211
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50175.3398 - mae: 50175.3398 - val_loss: 50287.6328 - val_mae: 50287.6328
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49789.5781 - mae: 49789.5781 - val_loss: 50277.6836 - val_mae: 50277.6836
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49467.2578 - mae: 49467.2578 - val_loss: 50275.6367 - val_mae: 50275.6367
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49634.3477 - mae: 49634.3477 - val_loss: 50282.3008 - val_mae: 50282.3008
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49964.6914 - mae: 49964.6914 - val_loss: 50281.6562 - val_mae: 50281.6562
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49804.5664 - mae: 49804.5664 - val_loss: 50269.3594 - val_mae: 50269.3594
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49042.8516 - mae: 49042.8516 - val_loss: 50293.2539 - val_mae: 50293.2539
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49747.7695 - mae: 49747.7695 - val_loss: 50283.0195 - val_mae: 50283.0195
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49716.4023 - mae: 49716.4023 - val_loss: 50277.0234 - val_mae: 50277.0234
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49165.3320 - mae: 49165.3320 - val_loss: 50285.0898 - val_mae: 50285.0898
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49230.7617 - mae: 49230.7617 - val_loss: 50292.9336 - val_mae: 50292.9336
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49670.2148 - mae: 49670.2148 - val_loss: 50295.7969 - val_mae: 50295.7969
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49160.2188 - mae: 49160.2188 - val_loss: 50302.1562 - val_mae: 50302.1562
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49541.3750 - mae: 49541.3750 - val_loss: 50302.1328 - val_mae: 50302.1328
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49216.8906 - mae: 49216.8906 - val_loss: 50290.1367 - val_mae: 50290.1367
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49040.6367 - mae: 49040.6367 - val_loss: 50296.3984 - val_mae: 50296.3984

In [17]:
%load_ext tensorboard

In [18]:
%tensorboard --logdir regressionlogs/fit